sudo: true
language: php
dist: trusty
php:
  - '7.1'
  - '7.2'
  - '7.3'

services:
  - memcached

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - mkdir build
  - phpenv config-rm xdebug.ini
  - bash ci/install.sh
  - echo $(php -r "echo SWOOLE_VERSION;")

install:
  - composer install

script:
  - php tests/run.php -c phpunit.xml
